apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env.headlessServiceName }}
  labels:
    {{- include "kv.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "kv.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http