apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kv.fullname" . }}
  labels:
    {{- include "kv.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.env.headlessServiceName }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kv.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "10Mi" #
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kv.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: kv
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.volume.path }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: DB_PATH
              value: {{ .Values.persistence.db.path }}
            - name: PORT
              value: {{ .Values.env.port | quote }}
            - name: REPLICAS
              value: {{ .Values.replicaCount | quote }}
            - name: HEADLESS_SERVICE
              value: {{ .Values.env.headlessServiceName | quote }}
            - name: POD_NAME
              valueFrom:
                fieldRef: { fieldPath: metadata.name }
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef: { fieldPath: metadata.namespace }
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 1
            periodSeconds: 2
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}